name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        find . ! -path . -type d -exec sh -c 'cd $1 && [ -f Cargo.toml ] && cargo build --verbose' _ {} \;
    - name: Run tests
      run: |
        find . ! -path . -type d -exec sh -c 'cd $1 && [ -f Cargo.toml ] && cargo test --verbose' _ {} \; 
