name: Rust - build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run tests?'
        required: true
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Expose event
      env:
        RUN_TESTS: ${{ inputs.runTests }}
      run: |
        echo "${{ github.event_name }}"
    - name: Build
      run: |
       echo "Run tests? [$RUN_TESTS]"
       find . ! -path '*/\.*' -type d -mindepth 1 -maxdepth 1 \
       -exec sh -c 'ret=0; for n; do cargo build --verbose --manifest-path $n/Cargo.toml; ret=$(($?+$ret)); done; exit $ret' _ {} +
    - name: Run tests
      env:
        RUN_TESTS: ${{ inputs.runTests }}
      run: |
        echo "Run tests: $RUN_TESTS"
        if [[ "${{ github.event_name }}" == "push" || "$RUN_TESTS" == "true" ]]; then
          find . ! -path '*/\.*' -type d -mindepth 1 -maxdepth 1 \
        -exec sh -c 'ret=0; for n; do cargo test --manifest-path $n/Cargo.toml; ret=$(($?+$ret)); done; exit $ret' _ {} +
        else
          echo "Test skipped."
        fi
